services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/dev-crx-github-pr:cached
    command: sleep infinity
    shm_size: '2gb'
    cap_add:
      - SYS_ADMIN
